//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OMS.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدخول محظور.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية الجردية.
        /// </summary>
        public static string ActualQty {
            get {
                return ResourceManager.GetString("ActualQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تفاصيل العدسة.
        /// </summary>
        public static string AddLensDetails {
            get {
                return ResourceManager.GetString("AddLensDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lesnse.
        /// </summary>
        public static string AddLesnse {
            get {
                return ResourceManager.GetString("AddLesnse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة جديد.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة منتج جديد.
        /// </summary>
        public static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الفروع.
        /// </summary>
        public static string AllBranches {
            get {
                return ResourceManager.GetString("AllBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم المسموح.
        /// </summary>
        public static string AllowedDiscount {
            get {
                return ResourceManager.GetString("AllowedDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} موجود بالفعل.
        /// </summary>
        public static string AlreadyExistsFormat {
            get {
                return ResourceManager.GetString("AlreadyExistsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالعربية.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحساب البنكي.
        /// </summary>
        public static string BankAccountNo {
            get {
                return ResourceManager.GetString("BankAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البنك.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باركود.
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفواتير.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعار الفرع.
        /// </summary>
        public static string BranchLogo {
            get {
                return ResourceManager.GetString("BranchLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الماركة.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك حذف هذا العنصر لانه مستخدم في عناصر اخرى.
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقدا.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأصناف.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر التحويل.
        /// </summary>
        public static string ChangeRate {
            get {
                return ResourceManager.GetString("ChangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف الألوان.
        /// </summary>
        public static string ColorCategory {
            get {
                return ResourceManager.GetString("ColorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل التجاري.
        /// </summary>
        public static string CommercialNumber {
            get {
                return ResourceManager.GetString("CommercialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الشركة بالعربية.
        /// </summary>
        public static string CompanyNameAr {
            get {
                return ResourceManager.GetString("CompanyNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الشركة بالإنجليزية.
        /// </summary>
        public static string CompanyNameEn {
            get {
                return ResourceManager.GetString("CompanyNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الموظفين.
        /// </summary>
        public static string ContactPersons {
            get {
                return ResourceManager.GetString("ContactPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق النسخ.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price.
        /// </summary>
        public static string CostPrice {
            get {
                return ResourceManager.GetString("CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدول.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالات المرضية للعميل.
        /// </summary>
        public static string CustomerDiseases {
            get {
                return ResourceManager.GetString("CustomerDiseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكتروني العميل.
        /// </summary>
        public static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشوفات العميل.
        /// </summary>
        public static string CustomerExaminations {
            get {
                return ResourceManager.GetString("CustomerExaminations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال العميل.
        /// </summary>
        public static string CustomerMobile {
            get {
                return ResourceManager.GetString("CustomerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العميل.
        /// </summary>
        public static string CustomerNo {
            get {
                return ResourceManager.GetString("CustomerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتريات العميل.
        /// </summary>
        public static string CustomerPurchases {
            get {
                return ResourceManager.GetString("CustomerPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوة CYL من.
        /// </summary>
        public static string CYLFrom {
            get {
                return ResourceManager.GetString("CYLFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوة CYL إلى.
        /// </summary>
        public static string CYLTo {
            get {
                return ResourceManager.GetString("CYLTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الملف.
        /// </summary>
        public static string DataFile {
            get {
                return ResourceManager.GetString("DataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة الاساسية.
        /// </summary>
        public static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوف يتم حذف هذا العنصر, هل تريد الاستمرار؟.
        /// </summary>
        public static string DeleteConfirmationMsg {
            get {
                return ResourceManager.GetString("DeleteConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإستلام.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإهلاك المخزنى.
        /// </summary>
        public static string Depreciation {
            get {
                return ResourceManager.GetString("Depreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى فرع.
        /// </summary>
        public static string DestinationWarehouse {
            get {
                return ResourceManager.GetString("DestinationWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل / إضافة جديد.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع .
        /// </summary>
        public static string DetailsType {
            get {
                return ResourceManager.GetString("DetailsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيقاف تنبيهات رسائل البريد الالكتروني.
        /// </summary>
        public static string DisableEmailNotifications {
            get {
                return ResourceManager.GetString("DisableEmailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيقاف تنبيهات رسائل الجوال.
        /// </summary>
        public static string DisableSMSNotifications {
            get {
                return ResourceManager.GetString("DisableSMSNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        public static string DocNo {
            get {
                return ResourceManager.GetString("DocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الطبيب.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأطباء.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنزيل صيغة الملف.
        /// </summary>
        public static string DownloadTemplate {
            get {
                return ResourceManager.GetString("DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرسل إليه.
        /// </summary>
        public static string EamailReceivers {
            get {
                return ResourceManager.GetString("EamailReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد الإلكترونى.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بريد مرسل البريد الالكتروني.
        /// </summary>
        public static string EmailFromAddress {
            get {
                return ResourceManager.GetString("EmailFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم مرسل البريد الالكتروني.
        /// </summary>
        public static string EmailFromName {
            get {
                return ResourceManager.GetString("EmailFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظفين.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم بالانجليزية.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل الكود.
        /// </summary>
        public static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخل الاسم.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدوام المسائي.
        /// </summary>
        public static string EveningShift {
            get {
                return ResourceManager.GetString("EveningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الصرف.
        /// </summary>
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنتهاء.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد خارجى.
        /// </summary>
        public static string ExternalSupplier {
            get {
                return ResourceManager.GetString("ExternalSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاكس.
        /// </summary>
        public static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالى الرسوم.
        /// </summary>
        public static string FeesAmount {
            get {
                return ResourceManager.GetString("FeesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إنشاء الملف.
        /// </summary>
        public static string FileCreationDate {
            get {
                return ResourceManager.GetString("FileCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم ملف العميل.
        /// </summary>
        public static string FileNo {
            get {
                return ResourceManager.GetString("FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنة التخرج.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافي الفاتورة.
        /// </summary>
        public static string GroundTotal {
            get {
                return ResourceManager.GetString("GroundTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتف المنزل.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية.
        /// </summary>
        public static string IdentityNo {
            get {
                return ResourceManager.GetString("IdentityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستيراد بيانات.
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ: الحساب غير مفعل, من فضلك تواصل مع مدير النظام.
        /// </summary>
        public static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم بطاقة التأمين.
        /// </summary>
        public static string InsuranceCardNo {
            get {
                return ResourceManager.GetString("InsuranceCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد داخلى.
        /// </summary>
        public static string InternalSupplier {
            get {
                return ResourceManager.GetString("InternalSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ: اسم المستخدم او كلمة المرور غير صحيح.
        /// </summary>
        public static string InvalidUserOrPass {
            get {
                return ResourceManager.GetString("InvalidUserOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جرد الفروع.
        /// </summary>
        public static string InventoryVerification {
            get {
                return ResourceManager.GetString("InventoryVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الفاتورة.
        /// </summary>
        public static string InvoiceAmount {
            get {
                return ResourceManager.GetString("InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الفاتورة.
        /// </summary>
        public static string InvoiceData {
            get {
                return ResourceManager.GetString("InvoiceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الفاتورة.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الفاتورة.
        /// </summary>
        public static string InvoiceStatus {
            get {
                return ResourceManager.GetString("InvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الفاتورة.
        /// </summary>
        public static string InvoiceTotal {
            get {
                return ResourceManager.GetString("InvoiceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإستلام.
        /// </summary>
        public static string IsDelivered {
            get {
                return ResourceManager.GetString("IsDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجب.
        /// </summary>
        public static string IsPositive {
            get {
                return ResourceManager.GetString("IsPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مطلوب.
        /// </summary>
        public static string IsRequiredFormat {
            get {
                return ResourceManager.GetString("IsRequiredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب حجز مبيعات.
        /// </summary>
        public static string IsSalesRequest {
            get {
                return ResourceManager.GetString("IsSalesRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت التسوية.
        /// </summary>
        public static string IsSettled {
            get {
                return ResourceManager.GetString("IsSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بدء العمل.
        /// </summary>
        public static string JoiningDate {
            get {
                return ResourceManager.GetString("JoiningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر كشف للعميل.
        /// </summary>
        public static string LastExamination {
            get {
                return ResourceManager.GetString("LastExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطر العدسة.
        /// </summary>
        public static string LensDiameter {
            get {
                return ResourceManager.GetString("LensDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول العدسات.
        /// </summary>
        public static string LensesTable {
            get {
                return ResourceManager.GetString("LensesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معامل اللإنكسار.
        /// </summary>
        public static string LensIndex {
            get {
                return ResourceManager.GetString("LensIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمك العدسة.
        /// </summary>
        public static string LensThisckness {
            get {
                return ResourceManager.GetString("LensThisckness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العدسة.
        /// </summary>
        public static string LensType {
            get {
                return ResourceManager.GetString("LensType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل العناصر.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعار الشركة.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الفروع.
        /// </summary>
        public static string ManageBranches {
            get {
                return ResourceManager.GetString("ManageBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الماركات.
        /// </summary>
        public static string ManageBrand {
            get {
                return ResourceManager.GetString("ManageBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الموديلات.
        /// </summary>
        public static string ManageBrands {
            get {
                return ResourceManager.GetString("ManageBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة التصنيفات.
        /// </summary>
        public static string ManageCategories {
            get {
                return ResourceManager.GetString("ManageCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة المدن.
        /// </summary>
        public static string ManageCities {
            get {
                return ResourceManager.GetString("ManageCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الألوان.
        /// </summary>
        public static string ManageColors {
            get {
                return ResourceManager.GetString("ManageColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الدول.
        /// </summary>
        public static string ManageCountries {
            get {
                return ResourceManager.GetString("ManageCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة العملات.
        /// </summary>
        public static string ManageCurrencies {
            get {
                return ResourceManager.GetString("ManageCurrencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة العملاء.
        /// </summary>
        public static string ManageCustomers {
            get {
                return ResourceManager.GetString("ManageCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الحالات المرضية.
        /// </summary>
        public static string ManageDiseases {
            get {
                return ResourceManager.GetString("ManageDiseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الأطباء.
        /// </summary>
        public static string ManageDoctors {
            get {
                return ResourceManager.GetString("ManageDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المجموعات.
        /// </summary>
        public static string ManageGroups {
            get {
                return ResourceManager.GetString("ManageGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الموديلات.
        /// </summary>
        public static string ManageModel {
            get {
                return ResourceManager.GetString("ManageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المناطق.
        /// </summary>
        public static string ManageRegions {
            get {
                return ResourceManager.GetString("ManageRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الموردين.
        /// </summary>
        public static string ManageSupplier {
            get {
                return ResourceManager.GetString("ManageSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الفروع.
        /// </summary>
        public static string ManageWarehouses {
            get {
                return ResourceManager.GetString("ManageWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخامة.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدسات الطبية.
        /// </summary>
        public static string MedicalLens {
            get {
                return ResourceManager.GetString("MedicalLens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المنتجات .
        /// </summary>
        public static string MedicalLensData {
            get {
                return ResourceManager.GetString("MedicalLensData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأدنى للكمية.
        /// </summary>
        public static string MinQty {
            get {
                return ResourceManager.GetString("MinQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموديل.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدوام الصباحي.
        /// </summary>
        public static string MorningShift {
            get {
                return ResourceManager.GetString("MorningShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفي الشخصي.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة كشف جديد.
        /// </summary>
        public static string NewExamination {
            get {
                return ResourceManager.GetString("NewExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات للحفظ.
        /// </summary>
        public static string NoDataToSave {
            get {
                return ResourceManager.GetString("NoDataToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد أخطاء.
        /// </summary>
        public static string NoErrors {
            get {
                return ResourceManager.GetString("NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ بيانات.
        /// </summary>
        public static string NoItemSaved {
            get {
                return ResourceManager.GetString("NoItemSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر المصنع.
        /// </summary>
        public static string OfficialPrice {
            get {
                return ResourceManager.GetString("OfficialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام ادارة البصريات.
        /// </summary>
        public static string OMS {
            get {
                return ResourceManager.GetString("OMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العملية.
        /// </summary>
        public static string OperationNo {
            get {
                return ResourceManager.GetString("OperationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسوم أخرى.
        /// </summary>
        public static string OtherFees {
            get {
                return ResourceManager.GetString("OtherFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوع.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة المدفوعة.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف الرئيسي.
        /// </summary>
        public static string ParentCategory {
            get {
                return ResourceManager.GetString("ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باور.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }

        public static string UsePeriod
        {
            get
            {
                return ResourceManager.GetString("UsePeriod", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري المعالجة.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصنف.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الأصناف.
        /// </summary>
        public static string ProductsData {
            get {
                return ResourceManager.GetString("ProductsData", resourceCulture);
            }
        }
        public static string CLData
        {
            get
            {
                return ResourceManager.GetString("CLData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to صورة الملف الشخصي.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم وكيل الشراء.
        /// </summary>
        public static string PurchaseAgentName {
            get {
                return ResourceManager.GetString("PurchaseAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة شراء.
        /// </summary>
        public static string PurchaseBill {
            get {
                return ResourceManager.GetString("PurchaseBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشراء.
        /// </summary>
        public static string PurchasePrice {
            get {
                return ResourceManager.GetString("PurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير المبيعات.
        /// </summary>
        public static string PurchaseReport {
            get {
                return ResourceManager.GetString("PurchaseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات الشراء.
        /// </summary>
        public static string PurchaseTrxs {
            get {
                return ResourceManager.GetString("PurchaseTrxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤهل.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتبقي.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكـــرني.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الطلب.
        /// </summary>
        public static string RequestData {
            get {
                return ResourceManager.GetString("RequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئول الفرع.
        /// </summary>
        public static string ResponseEmployee {
            get {
                return ResourceManager.GetString("ResponseEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر البيع.
        /// </summary>
        public static string RetailPrice {
            get {
                return ResourceManager.GetString("RetailPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية المرتجعة.
        /// </summary>
        public static string ReturnedQty {
            get {
                return ResourceManager.GetString("ReturnedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيعات.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مندوب البيع.
        /// </summary>
        public static string SalesAgent {
            get {
                return ResourceManager.GetString("SalesAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة البيع.
        /// </summary>
        public static string SalesInvoice {
            get {
                return ResourceManager.GetString("SalesInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مندوب المبيعات.
        /// </summary>
        public static string SalesManName {
            get {
                return ResourceManager.GetString("SalesManName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتجع مبيعات.
        /// </summary>
        public static string SalesReturn {
            get {
                return ResourceManager.GetString("SalesReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات البيع.
        /// </summary>
        public static string SalesTransaction {
            get {
                return ResourceManager.GetString("SalesTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- إختار --.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار الكل.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر الملف.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوية.
        /// </summary>
        public static string Settle {
            get {
                return ResourceManager.GetString("Settle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الاساسية.
        /// </summary>
        public static string SetupData {
            get {
                return ResourceManager.GetString("SetupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل اسم المستخدم وكلمة المرور للدخول للنظام.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل خروج.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهارات الاضافية.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فرع.
        /// </summary>
        public static string SourceWarehouse {
            get {
                return ResourceManager.GetString("SourceWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوة SPH من.
        /// </summary>
        public static string SPHFrom {
            get {
                return ResourceManager.GetString("SPHFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوة SPH إلى.
        /// </summary>
        public static string SPHTo {
            get {
                return ResourceManager.GetString("SPHTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموردين.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ فاتورة المورد.
        /// </summary>
        public static string SupplierInvoiceDate {
            get {
                return ResourceManager.GetString("SupplierInvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم فاتورة المورد.
        /// </summary>
        public static string SupplierInvoiceNo {
            get {
                return ResourceManager.GetString("SupplierInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموردين.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المورد.
        /// </summary>
        public static string SupplierType {
            get {
                return ResourceManager.GetString("SupplierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات النظام.
        /// </summary>
        public static string SystemConfigurations {
            get {
                return ResourceManager.GetString("SystemConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعدادات النظام.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم الضريبية.
        /// </summary>
        public static string TaxFees {
            get {
                return ResourceManager.GetString("TaxFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللقب.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى تاريخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الخصم.
        /// </summary>
        public static string TotalDiscountAmont {
            get {
                return ResourceManager.GetString("TotalDiscountAmont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد العناصر.
        /// </summary>
        public static string TotalItems {
            get {
                return ResourceManager.GetString("TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الكمية.
        /// </summary>
        public static string TotalQty {
            get {
                return ResourceManager.GetString("TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ العملية.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العملية.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية دفتريا.
        /// </summary>
        public static string TransQty {
            get {
                return ResourceManager.GetString("TransQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العملية.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الحساب.
        /// </summary>
        public static string UserAccount {
            get {
                return ResourceManager.GetString("UserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروع المستخدم.
        /// </summary>
        public static string UserBranches {
            get {
                return ResourceManager.GetString("UserBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الاتصال للمستخدم.
        /// </summary>
        public static string UserContacts {
            get {
                return ResourceManager.GetString("UserContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة المستخدم.
        /// </summary>
        public static string UserImage {
            get {
                return ResourceManager.GetString("UserImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين والصلاحيات.
        /// </summary>
        public static string UsersAndRoles {
            get {
                return ResourceManager.GetString("UsersAndRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضريبة القيمة المضافة.
        /// </summary>
        public static string VatAmount {
            get {
                return ResourceManager.GetString("VatAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الجرد.
        /// </summary>
        public static string VerificationDate {
            get {
                return ResourceManager.GetString("VerificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إصدار.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مخزون.
        /// </summary>
        public static string WarehouseAdd {
            get {
                return ResourceManager.GetString("WarehouseAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإهلاك المخزني.
        /// </summary>
        public static string WarehouseDispose {
            get {
                return ResourceManager.GetString("WarehouseDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسئول الفرع.
        /// </summary>
        public static string Warehouser {
            get {
                return ResourceManager.GetString("Warehouser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صرف مخزون.
        /// </summary>
        public static string WarehouseSubtract {
            get {
                return ResourceManager.GetString("WarehouseSubtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمليات الفروع.
        /// </summary>
        public static string WarehouseTransaction {
            get {
                return ResourceManager.GetString("WarehouseTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقل بين الفروع.
        /// </summary>
        public static string WarehouseTransfer {
            get {
                return ResourceManager.GetString("WarehouseTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole sell price .
        /// </summary>
        public static string WholeSell {
            get {
                return ResourceManager.GetString("WholeSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات العمل.
        /// </summary>
        public static string WokingHours {
            get {
                return ResourceManager.GetString("WokingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات العمل.
        /// </summary>
        public static string WorkData {
            get {
                return ResourceManager.GetString("WorkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكتروني العمل.
        /// </summary>
        public static string WorkEmail {
            get {
                return ResourceManager.GetString("WorkEmail", resourceCulture);
            }
        }
        public static string ManagePowers
        {
            get
            {
                return ResourceManager.GetString("ManagePowers", resourceCulture);
            }
        }
        public static string Value
        {
            get
            {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }

}
