//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.SalesTransactions = new HashSet<SalesTransaction>();
        }
    
        public long Id { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public Nullable<long> RegionId { get; set; }
        public Nullable<long> CityId { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<long> ImageId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual Region Region1 { get; set; }
        public virtual Upload Upload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTransaction> SalesTransactions { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual User User { get; set; }
    }
}
