//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDisease
    {
        public long Id { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> DiseaseId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Disease Disease { get; set; }
    }
}
