//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public long Id { get; set; }
        public string EmailBody { get; set; }
        public string EmailAddress { get; set; }
        public bool IsEmailSent { get; set; }
        public string ReceivingEmails { get; set; }
        public Nullable<long> AttachmentId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Attachment Attachment { get; set; }
    }
}
