//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RightSPH { get; set; }
        public string RightCYL { get; set; }
        public string RightAXIS { get; set; }
        public string RightCL { get; set; }
        public string LeftSPH { get; set; }
        public string LeftCYL { get; set; }
        public string LeftAXIS { get; set; }
        public string LeftCL { get; set; }
        public string IPD { get; set; }
        public string ADDValue { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> DoctorId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
