//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPageAction
    {
        public long Id { get; set; }
        public long GroupId { get; set; }
        public long PageActionId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual PageAction PageAction { get; set; }
    }
}
