//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalLensSalesDetail
    {
        public long Id { get; set; }
        public string Qty { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> VATValue { get; set; }
        public Nullable<double> SalesPrice { get; set; }
        public Nullable<long> SalesTransactionMasterID { get; set; }
        public Nullable<long> MedicalLensMasterId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<int> SPHId { get; set; }
        public Nullable<int> CYL { get; set; }
    
        public virtual SalesTransaction SalesTransaction { get; set; }
        public virtual SPH SPH { get; set; }
        public virtual MedicalLensMaster MedicalLensMaster { get; set; }
    }
}
