//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalLensPurchaseDetail
    {
        public long Id { get; set; }
        public string Qty { get; set; }
        public Nullable<decimal> OfficialUnitPrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> ChangeRate { get; set; }
        public Nullable<long> PurchaseTransactionMasterID { get; set; }
        public Nullable<long> MedicalLensMasterId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public Nullable<int> SphId { get; set; }
        public Nullable<int> CYL_0 { get; set; }
        public Nullable<int> CYL_0_25 { get; set; }
        public Nullable<int> CYL_0_5 { get; set; }
        public Nullable<int> CYL_0_75 { get; set; }
        public Nullable<int> CYL_1 { get; set; }
        public Nullable<int> CYL_1_25 { get; set; }
        public Nullable<int> CYL_1_5 { get; set; }
        public Nullable<int> CYL_1_75 { get; set; }
        public Nullable<int> CYL_2 { get; set; }
        public Nullable<int> CYL_2_25 { get; set; }
        public Nullable<int> CYL_2_5 { get; set; }
        public Nullable<int> CYL_2_75 { get; set; }
        public Nullable<int> CYL_3 { get; set; }
        public Nullable<int> CYL_3_25 { get; set; }
        public Nullable<int> CYL_3_5 { get; set; }
        public Nullable<int> CYL_3_75 { get; set; }
        public Nullable<int> CYL_4 { get; set; }
        public Nullable<int> CYL_4_25 { get; set; }
        public Nullable<int> CYL_4_5 { get; set; }
        public Nullable<int> CYL_4_75 { get; set; }
        public Nullable<int> CYL_5 { get; set; }
        public Nullable<int> CYL_5_25 { get; set; }
        public Nullable<int> CYL_5_5 { get; set; }
        public Nullable<int> CYL_5_75 { get; set; }
        public Nullable<int> CYL_6 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual MedicalLensMaster MedicalLensMaster { get; set; }
        public virtual PurchaseTransactionMaster PurchaseTransactionMaster { get; set; }
    }
}
