//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Power
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Power()
        {
            this.Products = new HashSet<Product>();
        }
    
        public long Id { get; set; }
        public string Value { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> ModelId { get; set; }
        public Nullable<long> BrandId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Model Model { get; set; }
        public virtual Power Power1 { get; set; }
        public virtual Power Power2 { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Brand Brand { get; set; }
    }
}
