//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.PurchaseTransactionDetails = new HashSet<PurchaseTransactionDetail>();
            this.SalesTransactionDetails = new HashSet<SalesTransactionDetail>();
            this.WarehouseTransactionDetails = new HashSet<WarehouseTransactionDetail>();
            this.WarehouseVerificationDetails = new HashSet<WarehouseVerificationDetail>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public Nullable<decimal> OfficialPrice { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<long> BrandId { get; set; }
        public Nullable<long> ModelId { get; set; }
        public Nullable<long> ColorId { get; set; }
        public Nullable<long> MaterialId { get; set; }
        public Nullable<long> GradeId { get; set; }
        public string Design { get; set; }
        public string Volume { get; set; }
        public Nullable<long> PowerId { get; set; }
        public Nullable<long> CLSPAndSolutionTypeId { get; set; }
        public Nullable<long> UsePeriodId { get; set; }
        public string BarCode { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<double> AllowedDiscount { get; set; }
        public Nullable<double> RetailPrice { get; set; }
        public Nullable<double> WholeSellPrice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Material Material { get; set; }
        public virtual Model Model { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual CLSPAndSolutionType CLSPAndSolutionType { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual UsePeriod UsePeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseTransactionDetail> PurchaseTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTransactionDetail> SalesTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseTransactionDetail> WarehouseTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseVerificationDetail> WarehouseVerificationDetails { get; set; }
        public virtual Power Power { get; set; }
    }
}
