//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTransactionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseTransactionMaster()
        {
            this.MedicalLensPurchaseDetails = new HashSet<MedicalLensPurchaseDetail>();
            this.PurchaseTransactionDetails = new HashSet<PurchaseTransactionDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> SupplierInvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public string PurchaseAgentName { get; set; }
        public Nullable<decimal> TaxFees { get; set; }
        public Nullable<decimal> OtherFees { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> FeesAmount { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Notes { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalLensPurchaseDetail> MedicalLensPurchaseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseTransactionDetail> PurchaseTransactionDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
