//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReportView
    {
        public Nullable<int> ProductQty { get; set; }
        public Nullable<decimal> ProductChangeRate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ProductCode { get; set; }
        public string productNameAr { get; set; }
        public string productNameEn { get; set; }
        public Nullable<decimal> ProductPurchasePrice { get; set; }
        public long SupplierId { get; set; }
        public string SupplierNameAr { get; set; }
        public string SupplierNameEn { get; set; }
        public long WarehouseId { get; set; }
        public string WarehouseNameAr { get; set; }
        public string WarehouseNameEn { get; set; }
        public string WarehouseAddress { get; set; }
    }
}
