//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTransactionDetail
    {
        public long Id { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> OfficialUnitPrice { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> ChangeRate { get; set; }
        public Nullable<long> PurchaseTransactionMasterID { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> CurrencyId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual PurchaseTransactionMaster PurchaseTransactionMaster { get; set; }
        public virtual Product Product { get; set; }
    }
}
