//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReportView
    {
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string Code { get; set; }
        public string productNameAr { get; set; }
        public string productNameEn { get; set; }
        public string SupplierNameAr { get; set; }
        public string SupplierNameEn { get; set; }
        public long Id { get; set; }
    }
}
