//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTrackingReportView
    {
        public string WarehouserName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string DocNo { get; set; }
        public string SalesAgentName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> CostAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public long Id { get; set; }
        public Nullable<long> WarehouseId { get; set; }
    }
}
