//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesTransaction()
        {
            this.MedicalLensSalesDetails = new HashSet<MedicalLensSalesDetail>();
            this.PurchaseTransactionPayments = new HashSet<PurchaseTransactionPayment>();
            this.SalesTransactionDetails = new HashSet<SalesTransactionDetail>();
            this.SalesTransactionPayments = new HashSet<SalesTransactionPayment>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DocNo { get; set; }
        public string SalesAgentName { get; set; }
        public string WarehouserName { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public Nullable<decimal> VATValue { get; set; }
        public Nullable<decimal> CostAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalLensSalesDetail> MedicalLensSalesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseTransactionPayment> PurchaseTransactionPayments { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTransactionDetail> SalesTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesTransactionPayment> SalesTransactionPayments { get; set; }
        public virtual Branch Branch { get; set; }
    }
}
