//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemErrorLog
    {
        public long Id { get; set; }
        public Nullable<int> Source { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string URL { get; set; }
        public string ExceptionDetails { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
