//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfiguration
    {
        public int Id { get; set; }
        public string CompanyNameAr { get; set; }
        public string CompanyNameEn { get; set; }
        public Nullable<bool> DisableSMSNotifications { get; set; }
        public Nullable<bool> DisableEmailNotifications { get; set; }
        public Nullable<bool> IsSmtpAuthenticated { get; set; }
        public string SmtpPort { get; set; }
        public Nullable<bool> SmtpEnableSSL { get; set; }
        public string EmailFromName { get; set; }
        public string SmtpServer { get; set; }
        public string SmtpUserName { get; set; }
        public string SmtpPassword { get; set; }
        public string EmailFromAddress { get; set; }
        public string ApplicationUrl { get; set; }
        public string SMSSenderName { get; set; }
        public Nullable<long> LogoId { get; set; }
    
        public virtual Upload Upload { get; set; }
    }
}
