//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.NotificationResponses = new HashSet<NotificationResponse>();
            this.NotificationSeens = new HashSet<NotificationSeen>();
            this.UserGroups = new HashSet<UserGroup>();
            this.UserPageActions = new HashSet<UserPageAction>();
            this.UserWarehouses = new HashSet<UserWarehouse>();
            this.Warehouses = new HashSet<Warehouse>();
            this.Branches = new HashSet<Branch>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public string IdentityNo { get; set; }
        public string Email { get; set; }
        public string WorkEmail { get; set; }
        public string HomePhone { get; set; }
        public string CurrentJob { get; set; }
        public string Qualification { get; set; }
        public string GraduationYear { get; set; }
        public string Skills { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ActivationCode { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.TimeSpan> MorningFrom { get; set; }
        public Nullable<System.TimeSpan> MorningTo { get; set; }
        public Nullable<System.TimeSpan> EveningFrom { get; set; }
        public Nullable<System.TimeSpan> EveningTo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> ImageId { get; set; }
        public Nullable<long> NationalityId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> JobId { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationResponse> NotificationResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationSeen> NotificationSeens { get; set; }
        public virtual Upload Upload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGroup> UserGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPageAction> UserPageActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWarehouse> UserWarehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches { get; set; }
    }
}
