//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseProductsView
    {
        public long WarehouseID { get; set; }
        public string WarehouseAr { get; set; }
        public string WarehouseEn { get; set; }
        public long ProductID { get; set; }
        public string ProductAr { get; set; }
        public string ProductEn { get; set; }
        public int total { get; set; }
    }
}
