//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseVerificationDetail
    {
        public long Id { get; set; }
        public Nullable<int> TransQty { get; set; }
        public Nullable<int> ActualQty { get; set; }
        public Nullable<decimal> UnitOfficialPrice { get; set; }
        public Nullable<long> WarehouseVerificationId { get; set; }
        public Nullable<long> MedicalLensIMasterd { get; set; }
        public Nullable<long> ProductId { get; set; }
    
        public virtual MedicalLensMaster MedicalLensMaster { get; set; }
        public virtual WarehouseVerification WarehouseVerification { get; set; }
        public virtual Product Product { get; set; }
    }
}
