//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DAL.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseVerification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseVerification()
        {
            this.WarehouseVerificationDetails = new HashSet<WarehouseVerificationDetail>();
        }
    
        public long Id { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string WarehouserName { get; set; }
        public bool IsSettled { get; set; }
        public string Notes { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseVerificationDetail> WarehouseVerificationDetails { get; set; }
    }
}
