//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commons.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Commons.Framework.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully.
        /// </summary>
        internal static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added successfully.
        /// </summary>
        internal static string AddSuccessFormat {
            get {
                return ResourceManager.GetString("AddSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed file types: .
        /// </summary>
        internal static string AllowedExtensions {
            get {
                return ResourceManager.GetString("AllowedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic letters only are allowed for {0}.
        /// </summary>
        internal static string ArabicLettersOnlyErrorMessage {
            get {
                return ResourceManager.GetString("ArabicLettersOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق.
        /// </summary>
        internal static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإنشاء بنجاح.
        /// </summary>
        internal static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء {0} بنجاح.
        /// </summary>
        internal static string CreateSuccessFormat {
            get {
                return ResourceManager.GetString("CreateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف {0} بنجاح.
        /// </summary>
        internal static string DeleteSuccessFormat {
            get {
                return ResourceManager.GetString("DeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الملف.
        /// </summary>
        internal static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        internal static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل {0} بنجاح.
        /// </summary>
        internal static string EditSuccessFormat {
            get {
                return ResourceManager.GetString("EditSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إرفاق ملف فارغ..
        /// </summary>
        internal static string EmptyAttachmentIsNotAllowedErrorMessage {
            get {
                return ResourceManager.GetString("EmptyAttachmentIsNotAllowedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} لا يقبل سوى أحرف إنجليزية.
        /// </summary>
        internal static string EnglishLettersOnlyErrorMessage {
            get {
                return ResourceManager.GetString("EnglishLettersOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أبعاد الصورة غير صحيحة. الحد الأقصى للأبعاد المسموحة هي  {0}X{1}..
        /// </summary>
        internal static string FileImageDimensionsErrorMessage {
            get {
                return ResourceManager.GetString("FileImageDimensionsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المرفق ليس صورة صحيحة. برجاء إرفاق ملف صورة.
        /// </summary>
        internal static string FileNotValidImageErrorMessage {
            get {
                return ResourceManager.GetString("FileNotValidImageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الملف غير مسموح. الحد الأقصى لحجم الملف هو {0} ميجا بايت.
        /// </summary>
        internal static string FileSizeErrorMessage {
            get {
                return ResourceManager.GetString("FileSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ملف غير صحيح. برجاء إرفاق ملف من نوع {0} فقط.
        /// </summary>
        internal static string FileTypeErrorMessage {
            get {
                return ResourceManager.GetString("FileTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميلادي.
        /// </summary>
        internal static string Gregorian {
            get {
                return ResourceManager.GetString("Gregorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة التاريخ غير صحيحة.
        /// </summary>
        internal static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر المطلوب غير موجود بالنظام.
        /// </summary>
        internal static string ItemNotFoundError {
            get {
                return ResourceManager.GetString("ItemNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على {0} بالنظام.
        /// </summary>
        internal static string ItemNotFoundErrorFormat {
            get {
                return ResourceManager.GetString("ItemNotFoundErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحداثيات الموقع الجغرافي غير صحيحة.
        /// </summary>
        internal static string LocationLatLonErrorMessage {
            get {
                return ResourceManager.GetString("LocationLatLonErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى لحجم الملف هو.
        /// </summary>
        internal static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى لإرتفاع الصورة هو.
        /// </summary>
        internal static string MaxImageHeight {
            get {
                return ResourceManager.GetString("MaxImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى لعرض الصورة هو.
        /// </summary>
        internal static string MaxImageWidth {
            get {
                return ResourceManager.GetString("MaxImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميجا بايت.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب الموافقة على الشروط والاحكام.
        /// </summary>
        internal static string MustAcceptAgreement {
            get {
                return ResourceManager.GetString("MustAcceptAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون قيمة الحقل مختارة.
        /// </summary>
        internal static string MustBeTrueError {
            get {
                return ResourceManager.GetString("MustBeTrueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يسمح فقط بالأرقام.
        /// </summary>
        internal static string NumberOnlyErrorMessage {
            get {
                return ResourceManager.GetString("NumberOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معالجة الملفات ....
        /// </summary>
        internal static string ProcessingDroppedFiles {
            get {
                return ResourceManager.GetString("ProcessingDroppedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ {0} بنجاح.
        /// </summary>
        internal static string SaveSuccessFormat {
            get {
                return ResourceManager.GetString("SaveSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يسمح بكتابة سكريبت في حقل {0}.
        /// </summary>
        internal static string ScriptsNotAllowedErrorMessage {
            get {
                return ResourceManager.GetString("ScriptsNotAllowedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الملفات.
        /// </summary>
        internal static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجري.
        /// </summary>
        internal static string UmmAlqura {
            get {
                return ResourceManager.GetString("UmmAlqura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في حال لم تقم بإرفاق ملف سيتم المحافظة على الملف القديم.
        /// </summary>
        internal static string UploaderOptionalInEditMode {
            get {
                return ResourceManager.GetString("UploaderOptionalInEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يسمح فقط برقم سنة صحيح.
        /// </summary>
        internal static string YearOnlyErrorMessage {
            get {
                return ResourceManager.GetString("YearOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
